### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by Renay** [mdavranche/erine.email#1]
You should correct your syntax on dump.sql:

> CREATE TABLE `Users` (
>   `ID` int(7) unsigned NOT NULL AUTO_INCREMENT,
>   `Username` varchar(15) NOT NULL,
>   `first_name` varchar(15) NOT NULL,
>   `last_name` varchar(15) NOT NULL,
>   `Password` varchar(40) NOT NULL,
>   `Email` varchar(100) NOT NULL,
>   `Activated` tinyint(1) unsigned NOT NULL DEFAULT '0',
>   `Confirmation` char(40) NOT NULL DEFAULT '',
>   `RegDate` int(11) unsigned NOT NULL,
>   `LastLogin` int(11) unsigned NOT NULL DEFAULT '0',
>   PRIMARY KEY (`ID`),
>   UNIQUE KEY `Username` (`Username`)
> ) ENGINE=InnoDB;
> 

Field should begin with tiny letter. 
What does mean "RegDate"  ?

> `mailAddress` varchar(254) NOT NULL
>  `disposableMailAddress` varchar(254) DEFAULT NULL,,

s/mailAddress/emailAdress/

:)

**Comment by mdavranche** [comment]
Done. See commit 58afc2fca466accdcd3bfb6f1ba62d9367039e17.
Thanks for your report.
